version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    # On ajoute la configuration UTF-8MB4 ici pour accepter tous les caractères spéciaux
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_qcm

    ports:
      - "3307:3306"
    volumes:
      - qcm_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: qcm_app
    ports:
      - "8081:9090"
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # On s'assure que l'URL force bien l'UTF-8
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_qcm?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  qcm_db_data: