# ==============================================================
# CONFIGURATION DE L'APPLICATION
# ==============================================================
spring.application.name=qcm-platform

# ==============================================================
# CONFIGURATION MYSQL (LOCAL / DOCKER)
# ==============================================================
# IMPORTANT : Pour Docker, on utilise 'db' comme nom d'hote
spring.datasource.url=jdbc:mysql://localhost:3306/db_qcm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
# On laisse vide pour correspondre a la configuration Docker
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ==============================================================
# JPA / HIBERNATE
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================================
# SERVEUR
# ==============================================================
# Port interne au conteneur (Docker mappera le 8081 vers ce 9090)
server.port=9090

# ==============================================================
# THYMELEAF
# ==============================================================
spring.thymeleaf.cache=false

# ==============================================================
# LOGGING
# ==============================================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework=INFO

spring.security.user.name=user
spring.security.user.password=password